name: CI
on: push

env:
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

jobs:
  build:                                        # Job 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2               # Step 1.1
      - name: Build with Maven                  # Step 1.2
        run: mvn -B package

  report:                                       # Job 2
    needs: build                                
    runs-on: ubuntu-latest
    steps:
      - name: Slack Message                     # Step 2.1
        uses: hbfernandes/slack-action@master   
        with:
          args: |
            {
              "channel": "development",
              "text": "testing slack messaging"
            }