name: CI
on: release                                        # triggers

env:                                            # environment variables
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

jobs:
  build:                                        # Job 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2               # Step 1.1 (action)
      - name: Build with Maven                  # Step 1.2 (shell command)
        run: mvn -B package

  report:                                       # Job 2
    needs: build                                
    runs-on: ubuntu-latest
    steps:
    - name: Slack Message                       # Step 2.1 (action)
      uses: hbfernandes/slack-action@master   
      with:
        args: |
          {
            "channel": "development",
            "attachments": [
              {
                "mrkdwn_in": ["text"],
                "color": "#36a64f",
                "pretext": "Built branch ${{ github.ref }}",
                "author_name": "${{ github.actor }}",
                "author_link": "http://flickr.com/bobby/",
                "author_icon": "https://placeimg.com/16/16/people",
                "title": "${{ github.workflow }}",
                "title_link": "https://api.slack.com/",
                "thumb_url": "http://placekitten.com/g/200/200",
                "footer": "Github Actions",
                "footer_icon": "https://platform.slack-edge.com/img/default_application_icon.png",
                "ts": 123456789
              }
            ]
          }
