name: release check
on: 
  schedule:
    - cron: '*/5 * * * *'
  push:

env:
  # RELEASE_MESSAGE: 'chore(release): publish'
  RELEASE_MESSAGE: 'release'

jobs:
  # this method should work with all events (scheduled and push)
  release-check:                                        
    runs-on: ubuntu-latest
    steps:
      - name: Check 
        uses: actions/github-script@0.8.0
        with:
          script: |
            console.log('${{ github.event.head_commit.message }}')

            const commit = await github.repos.getCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha
            })

            const message = commit.data.commit.message
            if(message.includes('${{ env.RELEASE_MESSAGE }}')){
              console.log('A release of the current state has already been performed, not releasing.')

              await github.actions.cancelWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: ${{ github.run_id }}
              })
            }

  release-perform:
    needs: release-check
    runs-on: ubuntu-latest
    steps:
      - name: Perform Release
        run: echo 'do release'




            


