name: release check
on: repository_dispatch

env:
  # RELEASE_MESSAGE: 'chore(release): publish'
  RELEASE_MESSAGE: 'release'

jobs:
  # this method works with both scheduled and push events
  release-check:                                        
    runs-on: ubuntu-latest
    steps:
      - name: Release Check 
        uses: actions/github-script@0.8.0
        with:
          script: |
            const commit = await github.repos.getCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha
            })

            const message = commit.data.commit.message
            if(message.includes('${{ env.RELEASE_MESSAGE }}')){
              console.log('A release has already been performed, cancelling workflow...')

              await github.actions.cancelWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: ${{ github.run_id }}
              })
            }

  release-perform:
    needs: release-check
    runs-on: ubuntu-latest
    steps:
      - name: Perform Release
        run: echo 'do release'




            


