name: release check
on: 
  # repository_dispatch:
  #   types: [run]
  # release:
  # schedule:
  #   - cron: '*/5 * * * *'
  push:
    
env:
  # RELEASE_MESSAGE: 'chore(release): publish'
  RELEASE_MESSAGE: 'release'
  RELEASE_BRANCH: dev

jobs:
  # this method works with both scheduled and push events
  release-check:                                        
    runs-on: ubuntu-latest
    steps:
      - name: Release Check 
        uses: actions/github-script@0.8.0
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          script: |
            console.log(context.ref)

            //const commit = await github.repos.getCommit({
            //  owner: 'pentaho',
            //  repo: 'hv-uikit-react',
            //  ref: 'heads/master'
            //})
            
            //console.log(commit)

            const branch = await github.repos.getBranch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: context.ref
            })

            const message = branch.data.commit.commit.message
            console.log(message)